version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.37
    container_name: imdazpi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: imdazpiDB
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE